//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankIntouch
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string BankDescription { get; set; }
        public string AccountNumber { get; set; }
        public string EmployeeName { get; set; }
        public string Description { get; set; }
        public string UserComments { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> VAT { get; set; }
    }
}
