//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCaterAllen
    {
        public long FITID { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string TxnType { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
    }
}
