//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessAccountingEntities : DbContext
    {
        public BusinessAccountingEntities()
            : base("name=BusinessAccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Date> Date { get; set; }
        public virtual DbSet<DividendThreshold> DividendThreshold { get; set; }
        public virtual DbSet<Payee> Payee { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<InputCatalog> InputCatalog { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankEdit> BankEdit { get; set; }
        public virtual DbSet<ExpenseEdit> ExpenseEdit { get; set; }
        public virtual DbSet<PayeeMapping> PayeeMapping { get; set; }
        public virtual DbSet<BankCaterAllen> BankCaterAllen { get; set; }
        public virtual DbSet<BankIntouch> BankIntouch { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    }
}
