//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DividendThreshold
    {
        public int ThresholdID { get; set; }
        public string FinYear { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<decimal> TaxPct { get; set; }
        public Nullable<short> IsOptimumBand { get; set; }
        public Nullable<decimal> NetAmountCarryOver { get; set; }
    }
}
