//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string ContractReference { get; set; }
        public string ClientName { get; set; }
        public string InvoiceReference { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> VAT { get; set; }
    }
}
