//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public System.DateTime SalaryDate { get; set; }
        public string TaxCode { get; set; }
        public decimal TotalPay { get; set; }
        public decimal TaxDeducted { get; set; }
        public decimal EmployeeNIC { get; set; }
        public decimal EmployeePension { get; set; }
        public decimal SickPay { get; set; }
        public decimal ParentingPay { get; set; }
        public decimal StudentLoan { get; set; }
        public decimal NetPay { get; set; }
        public decimal EmployerNIC { get; set; }
        public decimal EmployerPension { get; set; }
    }
}
