//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public System.DateTime PostedDate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int TransactionTypeID { get; set; }
        public int PayeeID { get; set; }
        public string TransferType { get; set; }
        public decimal Amount { get; set; }
        public decimal EffectiveAmount { get; set; }
        public string TransactionSource { get; set; }
        public string SourceID { get; set; }
    }
}
