//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plutus.ETL.CS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public int TransactionTypeID { get; set; }
        public string Activity { get; set; }
        public string TransactionCategory { get; set; }
        public string TransactionSubCategory { get; set; }
    }
}
